paths:
  - https://gitlab.com/some/group/project.git
author:
  key: mail #mail,name
  duplicates: #sometimes one person signed by different names
    John: [ john, jon ]
files:
  includeRe: '' ##leave empty for all files
